server:
  port: 8483
  address: 0.0.0.0
#  servlet:
#    context-path: /fitherway-service
#    base-url: http://localhost:8483/fitherway-service/api

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: fitherway

  datasource:
    url: jdbc:postgresql://localhost:5432/fitherway
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

    access-token:
      expiration: 900000 # 15 minutes

    refresh-token:
      expiration: 86400000 # 1 day

app:
  filepath:
    windows: C:\\fit_her_way\\
    linux: /home/user/fit_her_way/
    mac: /Users/fit_her_way/


otp:
  length: 6         # Length of OTP
  alphanumeric: false # true for alphanumeric, false for numeric
  expiryInSeconds: 300 # OTP expiry time in seconds (5 minutes)

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /v1/swagger.html
